<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for local_ai_forum_assistant.
 *
 * @package   local_ai_forum_assistant
 * @copyright 2025 AI Forum Assistant
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['ai_forum_assistant:managesettings'] = 'Manage AI Assistant settings for a forum';
$string['ai_forum_assistant:viewdisclaimer'] = 'View the AI Assistant disclaimer on posts';
$string['disclaimer_default'] = 'This message was generated by an AI assistant. If you have further questions, please contact your instructor.';
$string['error_accessdenied'] = 'You do not have permission to manage AI Assistant settings for this forum.';
$string['error_apiunauthorized'] = 'OpenAI API key is invalid or does not have the required permissions. The AI assistant has been disabled globally. Please check your API key.';
$string['error_botuser_inactive'] = 'The configured AI bot user is inactive or deleted. Falling back to an available manager.';
$string['error_dailylimit'] = 'Daily request limit reached for forum {$a}. The AI assistant will resume tomorrow.';
$string['error_endpoint_blocked'] = 'The configured API endpoint host is not in the list of allowed providers (api.openai.com, *.openai.azure.com). Update the endpoint in the AI Forum Assistant global settings.';
$string['error_endpoint_https'] = 'The API endpoint must use HTTPS. Plain HTTP endpoints are not allowed.';
$string['error_invalidforum'] = 'Invalid forum ID supplied.';
$string['error_loopdetected'] = 'Loop detected: post author is the AI bot user. Skipping processing.';
$string['error_maxrequests_user_invalid'] = 'The per-user daily limit must be 0 (unlimited) or a positive integer.';
$string['error_noapikey'] = 'No OpenAI API key configured. Please set it in the AI Forum Assistant global settings.';
$string['error_nobotuser'] = 'No valid AI bot user found for forum {$a}. The AI assistant has been disabled for this forum.';
$string['error_ratelimit'] = 'OpenAI rate limit reached. The AI assistant will pause for one hour.';
$string['error_sitelimit'] = 'Site-wide daily API request limit reached. The AI assistant will resume tomorrow.';
$string['error_userlimit'] = 'Daily per-user response limit reached for user {$a}. The AI assistant will respond again to this user tomorrow.';
$string['forum_botuser'] = 'AI response user';
$string['forum_botuser_desc'] = 'The Moodle user that will post responses on behalf of the AI assistant. Must be an active user. Falls back to the site default if left empty.';
$string['forum_delay_response'] = 'Delay AI response by 1 hour';
$string['forum_delay_response_desc'] = 'When enabled, the AI response is queued and published approximately 1 hour after the student\'s post. Only applies in Immediate mode.';
$string['forum_delay_response_label'] = 'Wait 1 hour before publishing the AI reply';
$string['forum_disclaimer'] = 'Disclaimer text';
$string['forum_disclaimer_desc'] = 'Text appended to every AI response. Leave empty to disable the disclaimer.';
$string['forum_enabled'] = 'Enable AI Assistant in this forum';
$string['forum_enabled_desc'] = 'When enabled, the AI assistant will monitor and respond to student posts in this forum.';
$string['forum_maxrequests'] = 'Daily request limit for this forum';
$string['forum_maxrequests_desc'] = 'Maximum OpenAI API calls per day in this forum. When the limit is reached the assistant pauses until the next day.';
$string['forum_maxrequests_user'] = 'Daily request limit per user';
$string['forum_maxrequests_user_desc'] = 'Maximum AI responses a single user can receive per day in this forum. Set to 0 to disable the per-user limit.';
$string['forum_mode'] = 'Response mode';
$string['forum_mode_daily'] = 'Daily: send a consolidated daily summary';
$string['forum_mode_immediate'] = 'Immediate: reply to each student post individually';
$string['forum_notsaved'] = 'Settings could not be saved. Please try again.';
$string['forum_prompt_daily'] = 'Prompt for daily mode';
$string['forum_prompt_daily_desc'] = 'System prompt sent to OpenAI for the daily consolidated summary.';
$string['forum_prompt_daily_placeholder'] = 'You are an academic assistant. Summarise and respond to the day\'s forum interventions in a constructive and motivating way.';
$string['forum_prompt_immediate'] = 'Prompt for immediate mode';
$string['forum_prompt_immediate_desc'] = 'System prompt sent to OpenAI for each student post. Do not include language instructions; the system will always respond in the language of the student\'s message.';
$string['forum_prompt_immediate_placeholder'] = 'You are an academic assistant expert in [course topic]. Reply clearly, concisely and encouragingly.';
$string['forum_save'] = 'Save AI settings';
$string['forum_saved'] = 'AI Assistant settings saved successfully.';
$string['forum_settings_link'] = 'AI Assistant';
$string['forum_settings_title'] = 'AI Assistant Settings';
$string['free_locked_premium'] = 'Premium feature — available in the full version';
$string['free_locked_value'] = 'fixed in the free version';
$string['free_marketing_forum'] = '<strong>Want all these features?</strong><br>'
    . 'The locked options above — daily summary mode, delayed response, disclaimer text, '
    . 'and per-user daily limits — are available in the full version of this plugin. '
    . 'Contact <strong>RSMAX Consulting</strong> to upgrade.<br>'
    . 'Discover all AI-powered plugins developed to supercharge your Moodle at '
    . '<a href="https://pluginia.es/" target="_blank" rel="noopener noreferrer">pluginia.es</a>.';
$string['free_marketing_global'] = '<strong>Want all these features?</strong><br>'
    . 'This is the free community edition of AI Forum Assistant. '
    . 'To unlock the full feature set — custom AI model, per-user rate limits, daily summary mode, '
    . 'delayed responses, and more — contact <strong>RSMAX Consulting</strong>.<br>'
    . 'Discover all AI-powered plugins to supercharge your Moodle at '
    . '<a href="https://pluginia.es/" target="_blank" rel="noopener noreferrer">pluginia.es</a>.';
$string['pluginname'] = 'AI Forum Assistant';
$string['privacy:metadata:openai_api'] = 'AI Forum Assistant sends anonymised forum post content to the OpenAI API to generate automated responses. No names, email addresses or user IDs are transmitted. Post content may indirectly contain personal information written by students.';
$string['privacy:metadata:openai_api:forum_post_content'] = 'The plain-text body of a student\'s forum post, stripped of HTML and truncated. Sent to OpenAI to generate an automated reply. In daily mode multiple posts are batched and labelled with anonymous sequential identifiers.';
$string['privacy_reason'] = 'This plugin does not store personal data. Forum messages are anonymised before being sent to OpenAI and are not retained outside Moodle.';
$string['settings_apikey'] = 'OpenAI API Key';
$string['settings_apikey_desc'] = 'Your OpenAI API key. This value is stored encrypted and never exposed in logs or error pages.';
$string['settings_dailyhour'] = 'Daily Summary Hour';
$string['settings_dailyhour_desc'] = 'Hour of day (server time) at which the daily summary task will run. Applies to all forums in "daily" mode.';
$string['settings_defaultbot'] = 'Default Site-wide AI User';
$string['settings_defaultbot_desc'] = 'Username or user ID of the Moodle user that will act as the AI assistant when no specific user is configured at forum level. Create this user manually before configuring this setting.';
$string['settings_endpoint'] = 'API Endpoint';
$string['settings_endpoint_desc'] = 'Full URL of the OpenAI chat completions endpoint. Must use HTTPS and point to an allowed host (api.openai.com or *.openai.azure.com). Change only if you are using a supported compatible endpoint.';
$string['settings_heading'] = 'AI Forum Assistant – Global Settings';
$string['settings_heading_desc'] = 'Configure the global OpenAI integration settings. These values apply site-wide unless overridden at forum level.';
$string['settings_model'] = 'OpenAI Model';
$string['settings_model_desc'] = 'The OpenAI model to use for generating responses.';
$string['settings_siteratelimit'] = 'Enable Site-wide Rate Limit';
$string['settings_siteratelimit_desc'] = 'Limit the total number of OpenAI API calls per hour across the entire site.';
$string['settings_siteratelimit_max'] = 'Maximum requests per hour (site-wide)';
$string['settings_userratelimit'] = 'Enable Per-user Rate Limit';
$string['settings_userratelimit_desc'] = 'Limit the number of OpenAI API calls per user per hour.';
$string['settings_userratelimit_max'] = 'Maximum requests per hour (per user)';
$string['task_daily_name'] = 'AI Forum Assistant – Daily Summary';
$string['task_delayed_response_name'] = 'AI Forum Assistant – Delayed Response';
